// flow-typed signature: 20ab8bab6576f4def95dc8d63d9970fc
// flow-typed version: <<STUB>>/compare-versions_v3.4.0/flow_v0.91.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'compare-versions'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'compare-versions' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'compare-versions/test/compare' {
  declare module.exports: any;
}

declare module 'compare-versions/test/sort' {
  declare module.exports: any;
}

// Filename aliases
declare module 'compare-versions/index' {
  declare module.exports: $Exports<'compare-versions'>;
}
declare module 'compare-versions/index.js' {
  declare module.exports: $Exports<'compare-versions'>;
}
declare module 'compare-versions/test/compare.js' {
  declare module.exports: $Exports<'compare-versions/test/compare'>;
}
declare module 'compare-versions/test/sort.js' {
  declare module.exports: $Exports<'compare-versions/test/sort'>;
}
