// flow-typed signature: a6f2e172b8818b7cb4ff60318eaee3c5
// flow-typed version: <<STUB>>/esdoc-react-plugin_v^1.0.1/flow_v0.91.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'esdoc-react-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'esdoc-react-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'esdoc-react-plugin/src/Plugin' {
  declare module.exports: any;
}

// Filename aliases
declare module 'esdoc-react-plugin/src/Plugin.js' {
  declare module.exports: $Exports<'esdoc-react-plugin/src/Plugin'>;
}
