// flow-typed signature: 3a5f0aee2542901a6d564f007141b870
// flow-typed version: <<STUB>>/node-plop_v0.16.0/flow_v0.91.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'node-plop'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'node-plop' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'node-plop/lib/actions/_common-action-add-file' {
  declare module.exports: any;
}

declare module 'node-plop/lib/actions/_common-action-interface-check' {
  declare module.exports: any;
}

declare module 'node-plop/lib/actions/_common-action-utils' {
  declare module.exports: any;
}

declare module 'node-plop/lib/actions/add' {
  declare module.exports: any;
}

declare module 'node-plop/lib/actions/addMany' {
  declare module.exports: any;
}

declare module 'node-plop/lib/actions/append' {
  declare module.exports: any;
}

declare module 'node-plop/lib/actions/index' {
  declare module.exports: any;
}

declare module 'node-plop/lib/actions/modify' {
  declare module.exports: any;
}

declare module 'node-plop/lib/baked-in-helpers' {
  declare module.exports: any;
}

declare module 'node-plop/lib/fs-promise-proxy' {
  declare module.exports: any;
}

declare module 'node-plop/lib/generator-runner' {
  declare module.exports: any;
}

declare module 'node-plop/lib/index' {
  declare module.exports: any;
}

declare module 'node-plop/lib/node-plop' {
  declare module.exports: any;
}

declare module 'node-plop/lib/prompt-bypass' {
  declare module.exports: any;
}

// Filename aliases
declare module 'node-plop/lib/actions/_common-action-add-file.js' {
  declare module.exports: $Exports<'node-plop/lib/actions/_common-action-add-file'>;
}
declare module 'node-plop/lib/actions/_common-action-interface-check.js' {
  declare module.exports: $Exports<'node-plop/lib/actions/_common-action-interface-check'>;
}
declare module 'node-plop/lib/actions/_common-action-utils.js' {
  declare module.exports: $Exports<'node-plop/lib/actions/_common-action-utils'>;
}
declare module 'node-plop/lib/actions/add.js' {
  declare module.exports: $Exports<'node-plop/lib/actions/add'>;
}
declare module 'node-plop/lib/actions/addMany.js' {
  declare module.exports: $Exports<'node-plop/lib/actions/addMany'>;
}
declare module 'node-plop/lib/actions/append.js' {
  declare module.exports: $Exports<'node-plop/lib/actions/append'>;
}
declare module 'node-plop/lib/actions/index.js' {
  declare module.exports: $Exports<'node-plop/lib/actions/index'>;
}
declare module 'node-plop/lib/actions/modify.js' {
  declare module.exports: $Exports<'node-plop/lib/actions/modify'>;
}
declare module 'node-plop/lib/baked-in-helpers.js' {
  declare module.exports: $Exports<'node-plop/lib/baked-in-helpers'>;
}
declare module 'node-plop/lib/fs-promise-proxy.js' {
  declare module.exports: $Exports<'node-plop/lib/fs-promise-proxy'>;
}
declare module 'node-plop/lib/generator-runner.js' {
  declare module.exports: $Exports<'node-plop/lib/generator-runner'>;
}
declare module 'node-plop/lib/index.js' {
  declare module.exports: $Exports<'node-plop/lib/index'>;
}
declare module 'node-plop/lib/node-plop.js' {
  declare module.exports: $Exports<'node-plop/lib/node-plop'>;
}
declare module 'node-plop/lib/prompt-bypass.js' {
  declare module.exports: $Exports<'node-plop/lib/prompt-bypass'>;
}
